(function($){var methods={init:function(options){var p={side:'top',position:'0',fix:function(el,side){},unfix:function(el,side){}};if(options){$.extend(p,options);}return this.each(function(){var
menu=$(this),w=$(window),menuH,menuW,menuBorderTop,menuBorderBottom,menuBorderLeft,menuBorderRight,menuPaddingTop,menuPaddingBottom,menuPaddingLeft,menuPaddingRight,menuOffset,menuTop,menuLeft,menuMarginTop,menuMarginBottom,menuMarginLeft,menuMarginRight,menuCssPos,menuCssLeft,menuCssRight,menuCssBottom,menuCssTop,wH,wW,fMess=true,posLength=p.position.toString().split(' ').length,posTop=p.position,posBot=p.position;if(posLength==2){posTop=p.position.split(' ')[0];posBot=p.position.split(' ')[1]}menu.data({'posTop':posTop,'posBot':posBot,'update':'false'})
var sizeRecount=function(m){menuH=m.height();menuW=m.width();menuBorderTop=m.css('borderTopWidth');menuBorderBottom=m.css('borderBottomWidth');menuBorderLeft=m.css('borderLeftWidth');menuBorderRight=m.css('borderRightWidth');menuPaddingTop=m.css('paddingTop');menuPaddingBottom=m.css('paddingBottom');menuPaddingLeft=m.css('paddingLeft');menuPaddingRight=m.css('paddingRight');menuMarginTop=m.css('margin-top');menuMarginBottom=m.css('margin-bottom');menuMarginLeft=m.css('margin-left');menuMarginRight=m.css('margin-right');menuOffset=m.offset();menuTop=menuOffset.top;menuLeft=menuOffset.left;menuCssPos=m.css('position');menuCssLeft=m.css('left');menuCssRight=m.css('right');menuCssBottom=m.css('bottom');menuCssTop=m.css('top');};sizeRecount(menu);var unicId=new Date().getTime();var menuClear=menu.clone().attr('id',unicId).addClass('menuClear').css({}).css({visibility:'hidden',opacity:'0'});menu.after(menuClear);menu.data({'unicId':unicId})
var addFix=function(dinamicTop,side){menu.css({left:parseFloat(menuClear.offset().left)-parseFloat(menuClear.css('margin-left')),bottom:'auto',top:dinamicTop,position:'fixed',width:menuClear.width()}).addClass('menuFixar');menuClear.removeClass('elFixWidth')
if(fMess){fMess=false;if(p.fix!==undefined){p.fix(menu,side);}}}
var removeFix=function(side){menu.css({left:menuClear.css('left'),top:menuCssTop,bottom:'auto',right:menuCssRight,position:menuCssPos,width:menuClear.width()}).removeClass('menuFixar');menuClear.addClass('elFixWidth');if(!fMess){fMess=true;if(p.unfix!==undefined){p.unfix(menu,side);}}}
var dinamicTop;var side=p.side;var fixarDetect=function(){if(p.side=='bottom'){if(w.scrollTop()+w.height()<(menuTop+menuH+parseFloat(menuBorderTop)+parseFloat(menuBorderBottom)+parseFloat(menuPaddingTop)+parseFloat(menuPaddingBottom))+parseFloat(menu.data('posBot'))){dinamicTop=w.height()-(parseFloat(menu.data('posBot'))+menuH+parseFloat(menuBorderTop)+parseFloat(menuBorderBottom)+parseFloat(menuMarginTop)+parseFloat(menuPaddingTop)+parseFloat(menuPaddingBottom));addFix(dinamicTop,p.side);side=p.side;}else{removeFix(side);}}if(p.side=='top'){if((w.scrollTop()+parseFloat(menu.data('posTop')))>menuTop){dinamicTop=parseFloat(menu.data('posTop'))-parseFloat(menuMarginTop);addFix(dinamicTop,p.side);side=p.side;}else{removeFix(side);}}if(p.side=='all'){if(w.scrollTop()+w.height()<(menuTop+menuH+parseFloat(menuBorderTop)+parseFloat(menuBorderBottom)+parseFloat(menuPaddingTop)+parseFloat(menuPaddingBottom))+parseFloat(menu.data('posBot'))){dinamicTop=w.height()-(parseFloat(menu.data('posBot'))+menuH+parseFloat(menuBorderTop)+parseFloat(menuBorderBottom)+parseFloat(menuMarginTop)+parseFloat(menuPaddingTop)+parseFloat(menuPaddingBottom));addFix(dinamicTop,'bottom');side='bottom'}else{if((w.scrollTop()+parseFloat(menu.data('posTop')))>menuTop){dinamicTop=parseFloat(menu.data('posTop'))-parseFloat(menuMarginTop);addFix(dinamicTop,'top');side='top'}else{removeFix(side);}}}};if(p.side=='bottom'){menu.addClass('fixarBottom');}fixarDetect()
$(window).on('scroll',function(){fixarDetect();})
$(window).on('resize',function(){if(menu.is('.menuFixar')||menu.data('update')=='true'){menu.data({'update':'false'})
sizeRecount(menuClear);}else{sizeRecount(menu);}fixarDetect()})})},setPosition:function(newPos){var newPos=newPos.toString();var posLength=newPos.split(' ').length;var posTop=newPos;var posBot=newPos;if(posLength==2){posTop=newPos.split(' ')[0];posBot=newPos.split(' ')[1]}$(this).data({'posTop':posTop,'posBot':posBot})
$(window).trigger('resize')},getPosition:function(){return $(this).data('posTop')+' '+$(this).data('posBot');},update:function(){$('#'+$(this).data('unicId')).html($(this).html())
$(this).data({'updata':'true'})
$(window).trigger('resize');}};$.fn.liFixar=function(method){if(methods[method]){return methods[method].apply(this,Array.prototype.slice.call(arguments,1));}else if(typeof method==='object'||!method){return methods.init.apply(this,arguments);}else{$.error('Метод '+method+' в jQuery.liFixar не существует');}};})(jQuery);