<?php
/**
 * Export to PHP Array plugin for PHPMyAdmin
 * @version 0.2b
 */

//
// Database `red_site`
//

// `red_site`.`ws_articles`
$ws_articles = array(
  array('brand_id' => '4','brand' => 'ADIDAS'),
  array('brand_id' => '20','brand' => 'B.Young'),
  array('brand_id' => '27','brand' => 'Bench'),
  array('brand_id' => '28','brand' => 'Bershka'),
  array('brand_id' => '36','brand' => 'Blend of America'),
  array('brand_id' => '43','brand' => 'BON\'A PARTE'),
  array('brand_id' => '46','brand' => 'BROADWAY'),
  array('brand_id' => '49','brand' => 'BULLBOXER'),
  array('brand_id' => '50','brand' => 'C&A'),
  array('brand_id' => '53','brand' => 'cache-cache'),
  array('brand_id' => '62','brand' => 'CATBALOU'),
  array('brand_id' => '68','brand' => 'Christian Berg'),
  array('brand_id' => '87','brand' => 'Diesel'),
  array('brand_id' => '106','brand' => 'Everis'),
  array('brand_id' => '108','brand' => 'EXTASY'),
  array('brand_id' => '117','brand' => 'FRANK Q'),
  array('brand_id' => '119','brand' => 'FRANSA'),
  array('brand_id' => '126','brand' => 'GAS'),
  array('brand_id' => '146','brand' => 'HUMOR'),
  array('brand_id' => '152','brand' => 'ICHI'),
  array('brand_id' => '153','brand' => 'IDEXE'),
  array('brand_id' => '163','brand' => 'Jack&Jones'),
  array('brand_id' => '165','brand' => 'Jennyfer'),
  array('brand_id' => '189','brand' => 'Lee'),
  array('brand_id' => '207','brand' => 'MANGO'),
  array('brand_id' => '213','brand' => 'Massimo Dutti'),
  array('brand_id' => '219','brand' => 'Mexx'),
  array('brand_id' => '230','brand' => 'Morgan'),
  array('brand_id' => '232','brand' => 'Mustang'),
  array('brand_id' => '235','brand' => 'NAF NAF'),
  array('brand_id' => '241','brand' => 'NEW LOOK'),
  array('brand_id' => '247','brand' => 'Nina von C.'),
  array('brand_id' => '250','brand' => 'NO EXCESS'),
  array('brand_id' => '257','brand' => 'Object'),
  array('brand_id' => '260','brand' => 'Only'),
  array('brand_id' => '270','brand' => 'PLEASE'),
  array('brand_id' => '273','brand' => 'Promod'),
  array('brand_id' => '285','brand' => 'Replay'),
  array('brand_id' => '288','brand' => 'RG-512'),
  array('brand_id' => '292','brand' => 'Rinascimento'),
  array('brand_id' => '302','brand' => 'Selected'),
  array('brand_id' => '311','brand' => 'SISLEY'),
  array('brand_id' => '314','brand' => 'SOLID'),
  array('brand_id' => '315','brand' => 'SORBINO'),
  array('brand_id' => '320','brand' => 'Stradivarius'),
  array('brand_id' => '321','brand' => 'Street Gang'),
  array('brand_id' => '322','brand' => 'Street One'),
  array('brand_id' => '323','brand' => 'Sublevel'),
  array('brand_id' => '328','brand' => 'To Be Too'),
  array('brand_id' => '330','brand' => 'Tom Tailor'),
  array('brand_id' => '331','brand' => 'Tommy Hilfiger'),
  array('brand_id' => '333','brand' => 'Triumph'),
  array('brand_id' => '348','brand' => 'Vero Moda'),
  array('brand_id' => '352','brand' => 'VILA'),
  array('brand_id' => '356','brand' => 'WE'),
  array('brand_id' => '368','brand' => 'ZARA'),
  array('brand_id' => '370','brand' => 'ZU+ELEMENTS'),
  array('brand_id' => '380','brand' => 'H.I.S'),
  array('brand_id' => '384','brand' => 'Buffalo'),
  array('brand_id' => '386','brand' => 'Cars'),
  array('brand_id' => '391','brand' => 'Fresh Brand'),
  array('brand_id' => '396','brand' => 'Motivi'),
  array('brand_id' => '414','brand' => 'ATIVO'),
  array('brand_id' => '429','brand' => 'KangaROOS'),
  array('brand_id' => '431','brand' => 'Urban Surface'),
  array('brand_id' => '435','brand' => 'LASCANA'),
  array('brand_id' => '436','brand' => 'S.Oliver'),
  array('brand_id' => '453','brand' => 'Comma'),
  array('brand_id' => '469','brand' => 'Minelli'),
  array('brand_id' => '478','brand' => 'Original Marines'),
  array('brand_id' => '487','brand' => 'Cheap Monday'),
  array('brand_id' => '489','brand' => 'TAMARIS'),
  array('brand_id' => '496','brand' => 'Marco Tozzi'),
  array('brand_id' => '508','brand' => 'Esprit'),
  array('brand_id' => '518','brand' => 'One Green Elephant'),
  array('brand_id' => '555','brand' => 'Kaffe&Cream'),
  array('brand_id' => '570','brand' => 'Okaidi'),
  array('brand_id' => '578','brand' => 'KIABI'),
  array('brand_id' => '584','brand' => 'LCKR'),
  array('brand_id' => '586','brand' => 'ZIPPY'),
  array('brand_id' => '620','brand' => 'Made For Loving'),
  array('brand_id' => '635','brand' => 'WESC'),
  array('brand_id' => '690','brand' => 'RED'),
  array('brand_id' => '693','brand' => 'CRIVIT'),
  array('brand_id' => '721','brand' => 'LumberJack'),
  array('brand_id' => '734','brand' => 'ALIVE'),
  array('brand_id' => '738','brand' => 'GOLD LABEL'),
  array('brand_id' => '765','brand' => 'BENETTON'),
  array('brand_id' => '782','brand' => 'H&M'),
  array('brand_id' => '785','brand' => 'ZALANDO'),
  array('brand_id' => '799','brand' => 'Venti'),
  array('brand_id' => '863','brand' => 'SAINT TROPEZ'),
  array('brand_id' => '892','brand' => 'Geox'),
  array('brand_id' => '900','brand' => 'Bruno banani'),
  array('brand_id' => '907','brand' => 'Pier One'),
  array('brand_id' => '910','brand' => 'Vans'),
  array('brand_id' => '920','brand' => 'WRANGLER'),
  array('brand_id' => '936','brand' => 'YAMAMAY'),
  array('brand_id' => '937','brand' => 'TCM'),
  array('brand_id' => '953','brand' => 'Zero'),
  array('brand_id' => '960','brand' => 'Your Turn'),
  array('brand_id' => '973','brand' => 'Fracomina'),
  array('brand_id' => '975','brand' => 'Even&Odd'),
  array('brand_id' => '977','brand' => 'Lotto'),
  array('brand_id' => '994','brand' => 'Pepe Jeans'),
  array('brand_id' => '999','brand' => 'Kappa'),
  array('brand_id' => '1005','brand' => 'COS'),
  array('brand_id' => '1007','brand' => 'Mivite'),
  array('brand_id' => '1013','brand' => 'Dockers'),
  array('brand_id' => '1017','brand' => 'KicKers'),
  array('brand_id' => '1018','brand' => 'ANNA FIELD'),
  array('brand_id' => '1044','brand' => 'Lacoste'),
  array('brand_id' => '1050','brand' => 'Rockport'),
  array('brand_id' => '1068','brand' => 'Rieker'),
  array('brand_id' => '1080','brand' => 'DC'),
  array('brand_id' => '1082','brand' => 'Rebel'),
  array('brand_id' => '1084','brand' => 'DENIM REPUBLIC'),
  array('brand_id' => '1093','brand' => 'GSUS'),
  array('brand_id' => '1094','brand' => 'Gaialuna'),
  array('brand_id' => '1096','brand' => 'Cecil'),
  array('brand_id' => '1098','brand' => 'SCOTCH & SODA'),
  array('brand_id' => '1099','brand' => 'Sisters Point'),
  array('brand_id' => '1100','brand' => 'OXBOW'),
  array('brand_id' => '1102','brand' => 'Skechers'),
  array('brand_id' => '1113','brand' => 'Trespass'),
  array('brand_id' => '1115','brand' => 'John Reed'),
  array('brand_id' => '1122','brand' => 'LeMonada'),
  array('brand_id' => '1134','brand' => 'Head'),
  array('brand_id' => '1157','brand' => 'BONOBO'),
  array('brand_id' => '1162','brand' => 'LUPILU'),
  array('brand_id' => '1168','brand' => 'BEST BAND'),
  array('brand_id' => '1169','brand' => 'ALCOTT'),
  array('brand_id' => '1170','brand' => 'JACQUELINE de YONG'),
  array('brand_id' => '1174','brand' => 'DND'),
  array('brand_id' => '1183','brand' => 'Aldo'),
  array('brand_id' => '1193','brand' => 'D-STRUCT'),
  array('brand_id' => '1196','brand' => 'Polo Ralph Lauren'),
  array('brand_id' => '1235','brand' => 'CANADA HOUSE'),
  array('brand_id' => '1256','brand' => 'Regatta'),
  array('brand_id' => '1274','brand' => 'YUMI'),
  array('brand_id' => '1275','brand' => 'Uttam Boutique'),
  array('brand_id' => '1289','brand' => 'Pimkie'),
  array('brand_id' => '1293','brand' => 'River Island'),
  array('brand_id' => '1294','brand' => 'ZU-YSPANICI'),
  array('brand_id' => '1295','brand' => 'FUN&FUN'),
  array('brand_id' => '1297','brand' => 'HI-TEC'),
  array('brand_id' => '1298','brand' => 'Dress'),
  array('brand_id' => '1299','brand' => '2-Biz'),
  array('brand_id' => '1300','brand' => 'Despicable Me'),
  array('brand_id' => '1311','brand' => 'anerkjendt'),
  array('brand_id' => '1312','brand' => 'LINK'),
  array('brand_id' => '1317','brand' => 'UMBRO'),
  array('brand_id' => '1324','brand' => 'Mela'),
  array('brand_id' => '1329','brand' => 'Atlantic'),
  array('brand_id' => '1330','brand' => 'ASOS'),
  array('brand_id' => '1331','brand' => 'CARTOONS'),
  array('brand_id' => '1332','brand' => 'AIS'),
  array('brand_id' => '1337','brand' => '& other Stories'),
  array('brand_id' => '1338','brand' => 'Monte Cervino'),
  array('brand_id' => '1344','brand' => 'Minimum'),
  array('brand_id' => '1345','brand' => 'BENSON&CHERRY'),
  array('brand_id' => '1347','brand' => 'Klingel'),
  array('brand_id' => '1348','brand' => 'IANA'),
  array('brand_id' => '1355','brand' => 'Bellfield'),
  array('brand_id' => '1364','brand' => 'BLUE MOTION'),
  array('brand_id' => '1365','brand' => 'CRANE'),
  array('brand_id' => '1368','brand' => 'DPAM'),
  array('brand_id' => '1369','brand' => 'TOPSHOP'),
  array('brand_id' => '1373','brand' => 'WATSONS'),
  array('brand_id' => '1375','brand' => 'Royal Class'),
  array('brand_id' => '1381','brand' => 'NUMPH'),
  array('brand_id' => '1385','brand' => 'Le Coq Sportif'),
  array('brand_id' => '1386','brand' => 'Iska'),
  array('brand_id' => '1387','brand' => 'First & I'),
  array('brand_id' => '1390','brand' => 'Passionata'),
  array('brand_id' => '1391','brand' => 'LC WAIKIKI'),
  array('brand_id' => '1393','brand' => 'Calypso'),
  array('brand_id' => '1396','brand' => 'IKEA'),
  array('brand_id' => '1400','brand' => 'Roxy'),
  array('brand_id' => '1401','brand' => 'Quiksilver'),
  array('brand_id' => '1409','brand' => 'Circle Of Trust'),
  array('brand_id' => '1410','brand' => 'JUNKYARD'),
  array('brand_id' => '1414','brand' => 'Mayoral'),
  array('brand_id' => '1415','brand' => 'CORTEFIEL'),
  array('brand_id' => '1417','brand' => 'Lefties'),
  array('brand_id' => '1423','brand' => 'Feel X'),
  array('brand_id' => '1426','brand' => 'mama licious'),
  array('brand_id' => '1428','brand' => 'Molly Bracken'),
  array('brand_id' => '1433','brand' => 'RONNIE KAY'),
  array('brand_id' => '1434','brand' => 'Liliput'),
  array('brand_id' => '1436','brand' => 'Harvey&Jones'),
  array('brand_id' => '1439','brand' => 'Product'),
  array('brand_id' => '1442','brand' => 'BOSIDENG'),
  array('brand_id' => '1447','brand' => 'B GLAM'),
  array('brand_id' => '1450','brand' => 'ZIPPO'),
  array('brand_id' => '1451','brand' => 'Celio'),
  array('brand_id' => '1455','brand' => 'CROOP'),
  array('brand_id' => '1456','brand' => 'YAS'),
  array('brand_id' => '1457','brand' => 'Burton'),
  array('brand_id' => '1464','brand' => 'Digel'),
  array('brand_id' => '1470','brand' => 'Dorina'),
  array('brand_id' => '1473','brand' => 'DEHA'),
  array('brand_id' => '1476','brand' => 'K.O.I'),
  array('brand_id' => '1478','brand' => 'CROPP'),
  array('brand_id' => '1480','brand' => 'ADPT.'),
  array('brand_id' => '1481','brand' => 'MOSS COPENHAGEN'),
  array('brand_id' => '1482','brand' => 'Timezone'),
  array('brand_id' => '1483','brand' => 'Cedar Wood State'),
  array('brand_id' => '1484','brand' => 'Chicco'),
  array('brand_id' => '1485','brand' => 'Skin to Skin'),
  array('brand_id' => '1487','brand' => 'Coolcat'),
  array('brand_id' => '1491','brand' => 'JobStyle'),
  array('brand_id' => '1494','brand' => 'MIKE ELLIS'),
  array('brand_id' => '1495','brand' => 'ASTAR'),
  array('brand_id' => '1497','brand' => 'QUICK'),
  array('brand_id' => '1501','brand' => 'Color block'),
  array('brand_id' => '1502','brand' => 'ARTICLES'),
  array('brand_id' => '1504','brand' => 'NOON'),
  array('brand_id' => '1508','brand' => 'Urban Fox'),
  array('brand_id' => '1509','brand' => 'Esmara'),
  array('brand_id' => '1510','brand' => 'Livergy'),
  array('brand_id' => '1514','brand' => 'Sottotono'),
  array('brand_id' => '1515','brand' => 'Carlings'),
  array('brand_id' => '1516','brand' => 'Vailent'),
  array('brand_id' => '1517','brand' => 'DDP'),
  array('brand_id' => '1518','brand' => 'Salsa'),
  array('brand_id' => '1519','brand' => 'GREYSTONE FEMALE'),
  array('brand_id' => '1529','brand' => 'Distrikt'),
  array('brand_id' => '1532','brand' => 'polo vista'),
  array('brand_id' => '1533','brand' => 'UpFashion'),
  array('brand_id' => '1535','brand' => 'Straight Up'),
  array('brand_id' => '1536','brand' => 'Orfeo Paris'),
  array('brand_id' => '1538','brand' => 'Homebound'),
  array('brand_id' => '1539','brand' => 'Calvin Klein Jeans'),
  array('brand_id' => '1540','brand' => 'Deer Island'),
  array('brand_id' => '1541','brand' => 'Pepperts'),
  array('brand_id' => '1542','brand' => 'AND LESS'),
  array('brand_id' => '1543','brand' => 'Bien Bleu'),
  array('brand_id' => '1545','brand' => 'Coast Guard'),
  array('brand_id' => '1546','brand' => 'Out 4 Living'),
  array('brand_id' => '1547','brand' => 'BW'),
  array('brand_id' => '1548','brand' => 'Red Label'),
  array('brand_id' => '1551','brand' => 'Emmett'),
  array('brand_id' => '1552','brand' => 'London Fog'),
  array('brand_id' => '1554','brand' => 'ELLE'),
  array('brand_id' => '1557','brand' => 'Only&Sons'),
  array('brand_id' => '1558','brand' => 'Dare2B'),
  array('brand_id' => '1561','brand' => 'Goose Feel'),
  array('brand_id' => '1562','brand' => 'Colors of the world'),
  array('brand_id' => '1563','brand' => 'Beck&Hersey'),
  array('brand_id' => '1566','brand' => '1982'),
  array('brand_id' => '1569','brand' => 'Vision street wear'),
  array('brand_id' => '1570','brand' => 'Fatface'),
  array('brand_id' => '1571','brand' => 'Flame'),
  array('brand_id' => '1572','brand' => 'Big Star'),
  array('brand_id' => '1573','brand' => 'MADISON'),
  array('brand_id' => '1579','brand' => 'Kaporal'),
  array('brand_id' => '1580','brand' => 'Elmas'),
  array('brand_id' => '1582','brand' => 'Deepend'),
  array('brand_id' => '1583','brand' => 'On You by DDP'),
  array('brand_id' => '1584','brand' => 'Enrico Mori'),
  array('brand_id' => '1585','brand' => 'Pocopiano'),
  array('brand_id' => '1587','brand' => 'Melvin&Hamilton'),
  array('brand_id' => '1589','brand' => 'WALKX'),
  array('brand_id' => '1593','brand' => 'G-Star Raw'),
  array('brand_id' => '1595','brand' => 'Black Horse'),
  array('brand_id' => '1598','brand' => 'Oltre'),
  array('brand_id' => '1599','brand' => 'TWIST'),
  array('brand_id' => '1600','brand' => 'Mavi'),
  array('brand_id' => '1601','brand' => 'Noisy May'),
  array('brand_id' => '1602','brand' => 'Nudie Jeans'),
  array('brand_id' => '1603','brand' => 'Twenty8Twelve'),
  array('brand_id' => '1604','brand' => 'OXE'),
  array('brand_id' => '1605','brand' => 'Herrlicher'),
  array('brand_id' => '1606','brand' => 'Gümüs'),
  array('brand_id' => '1608','brand' => 'Maddox'),
  array('brand_id' => '1609','brand' => 'Maison Scotch'),
  array('brand_id' => '1611','brand' => '2nd one'),
  array('brand_id' => '1612','brand' => 'Five Units'),
  array('brand_id' => '1613','brand' => 'Casual Friday by Blend'),
  array('brand_id' => '1614','brand' => 'deep sleep'),
  array('brand_id' => '1615','brand' => 'kids ipek'),
  array('brand_id' => '1616','brand' => 'Vanity Fair'),
  array('brand_id' => '1617','brand' => 'Kids Boxer'),
  array('brand_id' => '1618','brand' => 'By Don'),
  array('brand_id' => '1619','brand' => 'Less.'),
  array('brand_id' => '1620','brand' => 'j.c.rags'),
  array('brand_id' => '1621','brand' => 'Ercan'),
  array('brand_id' => '1622','brand' => 'Scotch&Soda'),
  array('brand_id' => '1623','brand' => 'Gant'),
  array('brand_id' => '1624','brand' => 'Wolverine 1000 miles'),
  array('brand_id' => '1625','brand' => 'Dorothy Perkins'),
  array('brand_id' => '1626','brand' => 'mtng'),
  array('brand_id' => '1627','brand' => 'mint&berry'),
  array('brand_id' => '1630','brand' => 'Miss Selfudge'),
  array('brand_id' => '1633','brand' => 'Shoe the bear'),
  array('brand_id' => '1638','brand' => 'Mos Mosh'),
  array('brand_id' => '1639','brand' => 'Lost Ink'),
  array('brand_id' => '1641','brand' => 'Fancy Underwear'),
  array('brand_id' => '1642','brand' => 'Chapter'),
  array('brand_id' => '1643','brand' => 'Page One'),
  array('brand_id' => '1644','brand' => 'Dopo Dopo'),
  array('brand_id' => '1645','brand' => 'Gio Diev'),
  array('brand_id' => '1647','brand' => 'Deckard'),
  array('brand_id' => '1648','brand' => 'Rocket Dog'),
  array('brand_id' => '1649','brand' => 'Galliano'),
  array('brand_id' => '1650','brand' => 'Carhartt')
);
