<?php
/**
 * Export to PHP Array plugin for PHPMyAdmin
 * @version 0.2b
 */

//
// Database `red_site`
//

// `red_site`.`ws_articles`
$ws_articles = array(
  array('category_id' => '16'),
  array('category_id' => '30'),
  array('category_id' => '32'),
  array('category_id' => '35'),
  array('category_id' => '36'),
  array('category_id' => '37'),
  array('category_id' => '39'),
  array('category_id' => '40'),
  array('category_id' => '53'),
  array('category_id' => '55'),
  array('category_id' => '56'),
  array('category_id' => '57'),
  array('category_id' => '58'),
  array('category_id' => '60'),
  array('category_id' => '61'),
  array('category_id' => '62'),
  array('category_id' => '65'),
  array('category_id' => '67'),
  array('category_id' => '68'),
  array('category_id' => '69'),
  array('category_id' => '70'),
  array('category_id' => '73'),
  array('category_id' => '74'),
  array('category_id' => '75'),
  array('category_id' => '77'),
  array('category_id' => '78'),
  array('category_id' => '79'),
  array('category_id' => '80'),
  array('category_id' => '84'),
  array('category_id' => '106'),
  array('category_id' => '107'),
  array('category_id' => '113'),
  array('category_id' => '115'),
  array('category_id' => '137'),
  array('category_id' => '140'),
  array('category_id' => '141'),
  array('category_id' => '142'),
  array('category_id' => '143'),
  array('category_id' => '144'),
  array('category_id' => '146'),
  array('category_id' => '147'),
  array('category_id' => '148'),
  array('category_id' => '149'),
  array('category_id' => '150'),
  array('category_id' => '151'),
  array('category_id' => '152'),
  array('category_id' => '154'),
  array('category_id' => '155'),
  array('category_id' => '158'),
  array('category_id' => '163'),
  array('category_id' => '244'),
  array('category_id' => '249'),
  array('category_id' => '251'),
  array('category_id' => '253'),
  array('category_id' => '263'),
  array('category_id' => '273'),
  array('category_id' => '274'),
  array('category_id' => '275'),
  array('category_id' => '276'),
  array('category_id' => '277'),
  array('category_id' => '278'),
  array('category_id' => '279'),
  array('category_id' => '280'),
  array('category_id' => '281'),
  array('category_id' => '282'),
  array('category_id' => '283'),
  array('category_id' => '296'),
  array('category_id' => '297')
);
